name: Package Release

on:
  push:
    branches:
      - "main"
    paths:
      - "src/**"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3

      - name: "setup node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: |
          yarn
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
